Master:
  InstallPlugins:
    - workflow-multibranch:2.17
    - kubernetes:1.3.1
    - workflow-aggregator:2.5
    - workflow-job:2.17
    - credentials-binding:1.15
    - git:3.7.0
    - pipeline-aws:1.23
Agent:
  volumes:
  - type: HostPath
    hostPath: /var/run/docker.sock
    mountPath: /var/run/docker.sock